(in-package :project-euler)
(defun problem-19 ()
  (let ((current-day (encode-universal-time 0 0 1 1 1 1901))
	(last-day (encode-universal-time 0 0 1 1 1 2001))
	(num-sundays 0)
	(day-in-seconds (* 60 60 24)))
    (while (< current-day last-day)
      (multiple-value-bind (sec min hour day month year day-type dummy1 dummy2) (decode-universal-time current-day)
	(declare (ignore sec min hour month year dummy1 dummy2))
	(when (and (= day 1) (= 6 day-type))
	  (incf num-sundays)))
      (incf current-day day-in-seconds))
    num-sundays))
