(in-package :project-euler)

(defun chance-to-win-game-121 (n)
  (/ (iter (for i from 0 to (1- (expt 2 n)))
	 (let ((bin (number-to-binary i n)))
	   (when (> (funcall #'count 1 bin) (floor n 2))
	     (summing (reduce #'* (iter (for turn from 2)
					(for success in bin)
					(if (= success 1)
					    (collect 1)
					    (collect (1- turn))))))))) 
     (fact n)))
(defun fast-chance-to-win-game-121 (n)
  (iter (for i from 0 to (1- (expt 2 n)))
	))
(defun problem-121 (&optional (n 15))
  (floor (/ 1 (chance-to-win-game-121 n))))
